spring:
  config:
    import: classpath:application-default.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DateHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  profiles:
    active: prod
  flyway:
    ignore-migration-patterns: V5__.*,V6__.*,V10__.*
#  web:
#    resources:
#      static-locations: file:${app.avatar.upload-dir}/
sharing:
  debug: true
  log:
    path: ${user.home}/.sharing-v4/logs
  db:
    path: ${user.home}/.sharing-v4/db/sharing
  preview:
    text:
      maxFileSizeKb: 512

  dbCache:
    enable: true
server:
  port: 8088

  # application.properties
app:
    avatar:
      upload-dir: uploads/avatar/


